#!/bin/bash

# This script should be copied to .git/hooks/ in your local repo

# Staging Server
if [ `git rev-parse --abbrev-ref HEAD` == "staging" ]; then

    # Dump the database
    mysqldump -u root -proot ri_templates > ~/Users/mturner/Sites/6Deg/RealInteractive/Corporate/ri-templates/deploy/ri_templates.sql

fi

# Production Server
if [ `git rev-parse --abbrev-ref HEAD` == "production" ]; then

    # Path variables
    REMOTE_IMAGES_DIR="/var/www/vhosts/contest-templates.ca/httpdocs/library/images"
    LOCAL_IMAGES_DIR="/Users/mturner/Sites/6Deg/RealInteractive/Corporate/ri-templates/deploy/public-html/library/images/"

    # Delete remote backups (.deployment/backups) older than 7 days
    find /Users/mturner/Sites/6Deg/RealInteractive/Corporate/ri-templates/assets/database/production-backup/*.sql -mtime +7 | xargs rm -Rf;

    # Backup remote database to local assets dir
    mysqldump -h got2bunboring.ca -u got2b -p'8Noi4$a2' got2bunboring_website > /Users/mturner/Sites/6Deg/RealInteractive/Corporate/ri-templates/assets/database/production-backup/got2bunboring_website.sql

    # Backup remote user generated images to local /public-html/library/images
    rsync -avzhe ssh user@domain.ca:$REMOTE_IMAGES_DIR/usergen/ $LOCAL_IMAGES_DIR/usergen/
    rsync -avzhe ssh user@domain.ca:$REMOTE_IMAGES_DIR/usergen-fb/ $LOCAL_IMAGES_DIR/usergen-fb/

fi
